import { StyleSheet } from "react-native";
import { colors, spacing, radius, shadows } from "../theme";

export const screenStyles = StyleSheet.create({
  scrollArea: {
    padding: spacing.md,
    paddingBottom: 40,
    gap: spacing.md,
  },
  search: {
    height: 52,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    textAlign: "right",
    color: colors.textPrimary,
    ...shadows.sm,
  },
  primaryButton: {
    height: 56,
    borderRadius: radius.md,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row-reverse",
    gap: spacing.xs,
    ...shadows.md,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  grid: {
    flexDirection: "row-reverse",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  card: {
    width: "48.2%",
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    padding: spacing.md,
    ...shadows.sm,
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.5)",
  },
  blockCard: {
    width: "100%",
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    padding: spacing.md,
    ...shadows.sm,
  },
  previewImage: {
    width: "100%",
    height: 200,
    borderRadius: radius.md,
    marginTop: spacing.sm,
    backgroundColor: colors.border,
  },
  mediaEmptySlot: {
    height: 120,
    borderRadius: radius.md,
    borderWidth: 2,
    borderColor: colors.border,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  icon: {
    fontSize: 28,
    marginBottom: spacing.xs,
    textAlign: "right",
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "right",
  },
  categoryIconFrame: {
    width: 44,
    height: 44,
    borderRadius: radius.md,
    backgroundColor: colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.primary,
    textAlign: "right",
    marginTop: spacing.sm,
  },
  muted: {
    marginTop: 4,
    color: colors.textSecondary,
    textAlign: "right",
    fontSize: 13,
  },
  descriptionInput: {
    minHeight: 120,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    textAlign: "right",
    textAlignVertical: "top",
    color: colors.textPrimary,
    fontSize: 15,
  },
  rowBetween: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
  },
  verified: {
    color: colors.success,
    fontWeight: "700",
  },
  mapBox: {
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.sm,
  },
  mapPinRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: spacing.xs,
  },
  pinDot: {
    width: 14,
    height: 14,
    borderRadius: radius.full,
  },
  mapPinText: {
    color: colors.textPrimary,
    textAlign: "right",
    flex: 1,
    fontWeight: "500",
  },
  kpiRow: {
    flexDirection: "row-reverse",
    gap: spacing.sm,
  },
  kpiCard: {
    flex: 1,
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    padding: spacing.md,
    ...shadows.sm,
  },
  kpiValue: {
    marginTop: 4,
    fontSize: 26,
    fontWeight: "900",
    color: colors.primary,
    textAlign: "right",
  },
  adminComplaint: {
    gap: spacing.sm,
  },
  adminCardContainer: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    marginBottom: spacing.md,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(226, 232, 240, 0.4)",
    ...shadows.sm,
  },
  adminActions: {
    flexDirection: "row-reverse",
    gap: spacing.sm,
    padding: spacing.md,
    backgroundColor: "rgba(248, 250, 252, 0.5)",
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  actionBtn: {
    borderRadius: radius.md,
    borderWidth: 1.5,
    paddingVertical: 10,
    paddingHorizontal: 8,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row-reverse",
  },
  actionText: {
    fontWeight: "800",
    fontSize: 12,
  },
  profileHeader: {
    alignItems: "center",
    padding: spacing.xl,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    marginBottom: spacing.md,
    ...shadows.sm,
  },
  profileAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: spacing.md,
    ...shadows.md,
  },
  profileName: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.primary,
    textAlign: "center",
  },
  profileMeta: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 4,
  },
  notificationCard: {
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.sm,
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: spacing.md,
    borderRightWidth: 4,
    borderRightColor: colors.accent,
    ...shadows.sm,
  },
  profileBadge: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: colors.accentSoft,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyContainer: {
    padding: spacing.huge,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    marginTop: spacing.md,
  },
  emptyText: {
    marginTop: spacing.md,
    fontSize: 14,
    fontWeight: "600",
    color: colors.muted,
    textAlign: "center",
  },
});

